// frontend-vuejs/src/pages/Dashboard.vue
<script lang="ts">
import { defineComponent } from "vue"

import AddGoalForm from "../components/AddGoalForm.vue"
import Spinner from "../components/Spinner.vue"
import GoalList from "../components/GoalList.vue"

type Goal = { id: string; text: string; userId: string }

const myGoals: Partial<Goal>[] = [
  { id: "1", text: "First Goal", userId: "123" },
  { id: "2", text: "Second Goal", userId: "123" },
  { id: "3", text: "Third Goal", userId: "123" }
]

export default defineComponent({
  name: "DashboardPage",
  components: { AddGoalForm, Spinner, GoalList },
  data: () => ({
    isLoading: true,
    goals: [] as Partial<Goal>[],
    user: {
      id: "123",
      name: "John Doe"
    }
  }),
  methods: {
    handleAddGoal(text: string) {
      console.log("Goal", text)
    }
  },
  mounted() {
    setTimeout(() => {
      this.isLoading = false
      this.goals = myGoals
    }, 2000)
  }
})
</script>

<template>
  <div class="container">
    <section class="heading">
      <h1 class="page-title">Welcome {{ user ? user.name : "" }}</h1>
      <p>Goals Dashboard</p>
    </section>
    <AddGoalForm :userId="user.id" @addGoal="handleAddGoal" />
    <div v-if="isLoading">
      <Spinner />
    </div>
    <div v-else>
      <GoalList :goals="goals" />
    </div>
  </div>
</template>

// frontend-angular/src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit } from "@angular/core"
import type { Goal } from "src/types"

@Component({
    selector: "app-dashboard",
    templateUrl: "./dashboard.component.html"
})
export class DashboardComponent implements OnInit {
    public user = { name: "John Doe" }
    public isLoading = true

    public goals: Goal[] = []

    constructor() {}

    ngOnInit(): void {
        setTimeout(() => {
            this.goals = [
                { id: "1", text: "First goal", userId: "123" },
                { id: "2", text: "Second goal", userId: "123" },
                { id: "3", text: "Third goal", userId: "123" }
            ]
            this.isLoading = false
        }, 2000)
    }

    handleAddGoal(text: string) {
        console.log("ADD GOAL", text)
        const newGoal = {
            id: Math.floor(Math.random() * 100000).toString(),
            text,
            userId: "123"
        }
        this.goals.push(newGoal)
    }

    handleRemoveGoal(goalId: string) {
        this.goals = this.goals.filter(goal => goal.id !== goalId)
    }
}

<app-spinner *ngIf="isLoading"></app-spinner>
<div class="page-container">
    <section class="heading">
        <h1 class="page-title">Welcome {{ user && user.name ? user.name : "" }}</h1>
        <p>Goals Dashboard</p>
    </section>
    <app-add-goal-form (addGoal)="handleAddGoal($event)"></app-add-goal-form>
    <app-goal-list
        *ngIf="!isLoading"
        [goals]="goals"
        (removeGoal)="handleRemoveGoal($event)"
    ></app-goal-list>
</div>
