// frontend-vuejs/src/pages/Dashboard.vue
<script lang="ts">
import { defineComponent } from "vue"
import { v4 as uuid } from "uuid"

import AddGoalForm from "../components/AddGoalForm.vue"
import Spinner from "../components/Spinner.vue"
import GoalList from "../components/GoalList.vue"

export default defineComponent({
  name: "DashboardPage",
  components: { AddGoalForm, Spinner, GoalList },
  data: () => ({
    isLoading: true
  }),
  computed: {
    goals() {
      return this.$store.state.goals.goals || []
    },
    user() {
      return this.$store.state.auth.user || null
    }
  },
  methods: {
    handleAddGoal(text: string) {
      const newGoal = { id: uuid(), text, userId: this.user.id }
      this.$store.dispatch("addGoal", newGoal)
    },
    handleRemoveGoal(goalId: string) {
      this.$store.dispatch("removeGoal", goalId)
    }
  },
  async mounted() {
    if (!this.$store.state.auth.user) {
      this.$router.push("/signin")
      return
    }
    await this.$store.dispatch("getAllGoals")
    this.isLoading = false
  }
})
</script>

<template>
  <div class="container">
    <section class="heading">
      <h1 class="page-title">Welcome {{ user && user.name ? user.name : "" }}</h1>
      <p>Goals Dashboard</p>
    </section>
    <AddGoalForm @addGoal="handleAddGoal" />
    <div v-if="isLoading">
      <Spinner />
    </div>
    <div v-else>
      <GoalList :goals="goals" @removeGoal="handleRemoveGoal" />
    </div>
  </div>
</template>

// frontend-classes/src/pages/Dashboard.tsx
import { Component } from "react"
import { Navigate, NavigateFunction, useNavigate } from "react-router-dom"

import Spinner from "../components/Spinner"
import AddGoalForm from "../components/AddGoalForm"
import GoalListItem from "../components/GoalListItem"

import { useAppDispatch, useAppSelector } from "../app/hooks"
import { RootState } from "../app/store"
import { getAll, remove } from "../features/goals/goalThunks"
import { reset as resetGoals } from "../features/goals/goalSlice"
import { toast } from "react-toastify"
import { Goal, User } from "../features/types"

type ComponentProps = {
  isLoading: boolean
  user: User | null | undefined
  goals: Goal[]
  dispatch(args: any): any
  navigate: NavigateFunction
}

class DashboardComponent extends Component<ComponentProps> {
  constructor(props: ComponentProps) {
    super(props)
    this.props.dispatch(getAll())
  }

  componentWillUnmount = () => {
    this.props.dispatch(resetGoals())
  }

  handleDelete = (goalId: string) => {
    if (!goalId) {
      toast.error("No goalId to edit")
      return
    }
    this.props.dispatch(remove(goalId))
  }

  render() {
    const { isLoading, user, goals } = this.props
    if (isLoading) {
      return <Spinner />
    }
    if (!user || !user.id) {
      return <Navigate to="/signin" />
    }
    return (
      <div className="container">
        <section className="heading mb-5">
          <h1>Welcome {user && user.name}</h1>
          <p>Goals Dashboard</p>
        </section>
        <AddGoalForm userId={user.id} />
        <ul style={{ textAlign: "left", width: "70%", margin: "0 auto" }}>
          {goals.map((goal: Goal) => (
            <GoalListItem key={goal.id} goal={goal} handleDelete={this.handleDelete} />
          ))}
        </ul>
      </div>
    )
  }
}

export default () => {
  const navigate = useNavigate()
  const dispatch = useAppDispatch()
  const user = useAppSelector((state: RootState) => state.auth.user)
  const { goals, isLoading } = useAppSelector((state: RootState) => state.goals)
  return (
    <DashboardComponent
      isLoading={isLoading}
      user={user}
      goals={goals}
      dispatch={dispatch}
      navigate={navigate}
    />
  )
}
