// frontend-vuejs-setup/src/pages/Dashboard.vue
<script setup lang="ts">
import { computed, onMounted } from "vue"
import { v4 as uuid } from "uuid"
import { useStore } from "vuex"
import { useRouter } from "vue-router"

import AddGoalForm from "../components/AddGoalForm.vue"
import Spinner from "../components/Spinner.vue"
import GoalList from "../components/GoalList.vue"

const store = useStore()
const router = useRouter()

const goals = computed(() => store.state.goals.goals || [])
const user = computed(() => store.state.auth.user || null)

const handleAddGoal = (text: string) => {
    // @ts-ignore
    const newGoal = { id: uuid(), text, userId: user.id }
    store.dispatch("addGoal", newGoal)
}

const handleRemoveGoal = (goalId: string) => {
    store.dispatch("removeGoal", goalId)
}

onMounted(() => {
    //const lsUser = localStorage.getItem("user")
    //if (!lsUser) {
        //router.push("/signin")
        //return
    //}
    store.dispatch("getAllGoals")
})
</script>

<template>
    <div class="container">
        <section class="heading">
            <h1 class="page-title">Welcome {{ user && user.name ? user.name : "" }}</h1>
            <p>Goals Dashboard</p>
        </section>
        <AddGoalForm @addGoal="handleAddGoal" />
        <GoalList :goals="goals" @removeGoal="handleRemoveGoal" />
    </div>
</template>

// frontend/src/pages/Dashboard.tsx
import { useEffect } from "react"
import { useNavigate } from "react-router-dom"

import Spinner from "../components/Spinner"
import AddGoalForm from "../components/AddGoalForm"

import { useAppDispatch, useAppSelector } from "../app/hooks"
import { RootState } from "../app/store"
import { getAll } from "../features/goals/goalThunks"
import { reset as resetGoals } from "../features/goals/goalSlice"

const Dashboard = () => {
  const navigate = useNavigate()
  const dispatch = useAppDispatch()

  const { user } = useAppSelector((state: RootState) => state.auth)

  const { goals, isLoading } = useAppSelector((state: RootState) => state.goals)

  useEffect(() => {
    if (!user) {
      navigate("/signin")
    }
    dispatch(getAll())
    return () => {
      dispatch(resetGoals())
    }
  }, [user, navigate])

  if (!user || !user.id) return null

  return (
    <div className="container">
      <section className="heading mb-5">
        <h1>Welcome {user && user.name}</h1>
        <p>Goals Dashboard</p>
      </section>
      <AddGoalForm userId={user.id} />
      {isLoading && <Spinner />}
      {!isLoading && goals && (
        <ul>
          {goals.map(goal => (
            <li key={goal.id}>{goal.text}</li>
          ))}
        </ul>
      )}
    </div>
  )
}

export default Dashboard
