// frontend-vuejs/src/pages/Dashboard.vue
<script lang="ts">
import { defineComponent } from "vue"
import { v4 as uuid } from "uuid"

import AddGoalForm from "../components/AddGoalForm.vue"
import Spinner from "../components/Spinner.vue"
import GoalList from "../components/GoalList.vue"

export default defineComponent({
  name: "DashboardPage",
  components: { AddGoalForm, Spinner, GoalList },
  data: () => ({
    isLoading: true
  }),
  computed: {
    goals() {
      return this.$store.state.goals.goals || []
    },
    user() {
      return this.$store.state.auth.user || null
    }
  },
  methods: {
    handleAddGoal(text: string) {
      const newGoal = { id: uuid(), text, userId: this.user.id }
      this.$store.dispatch("addGoal", newGoal)
    },
    handleRemoveGoal(goalId: string) {
      this.$store.dispatch("removeGoal", goalId)
    }
  },
  async mounted() {
    if (!this.$store.state.auth.user) {
      this.$router.push("/signin")
      return
    }
    await this.$store.dispatch("getAllGoals")
    this.isLoading = false
  }
})
</script>

<template>
  <div class="container">
    <section class="heading">
      <h1 class="page-title">Welcome {{ user && user.name ? user.name : "" }}</h1>
      <p>Goals Dashboard</p>
    </section>
    <AddGoalForm @addGoal="handleAddGoal" />
    <div v-if="isLoading">
      <Spinner />
    </div>
    <div v-else>
      <GoalList :goals="goals" @removeGoal="handleRemoveGoal" />
    </div>
  </div>
</template>

// frontend/src/pages/Dashboard.tsx
import { useEffect } from "react"
import { useNavigate } from "react-router-dom"

import Spinner from "../components/Spinner"
import AddGoalForm from "../components/AddGoalForm"

import { useAppDispatch, useAppSelector } from "../app/hooks"
import { RootState } from "../app/store"
import { getAll } from "../features/goals/goalThunks"
import { reset as resetGoals } from "../features/goals/goalSlice"

const Dashboard = () => {
  const navigate = useNavigate()
  const dispatch = useAppDispatch()

  const { user } = useAppSelector((state: RootState) => state.auth)

  const { goals, isLoading } = useAppSelector((state: RootState) => state.goals)

  useEffect(() => {
    if (!user) {
      navigate("/signin")
    }
    dispatch(getAll())
    return () => {
      dispatch(resetGoals())
    }
  }, [user, navigate])

  if (!user || !user.id) return null

  return (
    <div className="container">
      <section className="heading mb-5">
        <h1>Welcome {user && user.name}</h1>
        <p>Goals Dashboard</p>
      </section>
      <AddGoalForm userId={user.id} />
      {isLoading && <Spinner />}
      {!isLoading && goals && (
        <ul>
          {goals.map(goal => (
            <li key={goal.id}>{goal.text}</li>
          ))}
        </ul>
      )}
    </div>
  )
}

export default Dashboard
