// frontend-angular/src/app/pages/signup/signup.component.ts
import { Component, OnInit } from "@angular/core"

@Component({
  selector: "app-signup",
  templateUrl: "./signup.component.html"
})
export class SignupComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<app-spinner *ngIf="isLoading"></app-spinner>
<div class="page-container">
    <section class="heading">
        <h1 class="page-title">
            <i class="fa-solid fa-right-to-bracket"></i>
            Sign Up
        </h1>
        <p>Inform your credentials to access the dashboard</p>
    </section>
    <section class="form">
        <form (submit)="handleSubmit()">
            <div class="form-group">
                <label class="label-block">Name</label>
                <input
                    type="text"
                    [(ngModel)]="name"
                    name="name"
                    class="form-text"
                    placeholder="Your full name"
                    required
                />
            </div>
            <div class="form-group">
                <label class="label-block">E-mail</label>
                <input
                    type="email"
                    [(ngModel)]="email"
                    name="email"
                    class="form-text"
                    placeholder="Enter an E-mail address"
                    required
                />
            </div>
            <div class="form-group">
                <label class="label-block">Phone</label>
                <input
                    type="text"
                    [(ngModel)]="phone"
                    name="phoen"
                    class="form-text"
                    placeholder="Phone number like: 999-999-9999"
                    pattern="[0-9]{3}-[0-9]{3}-[0-9]{4}"
                    required
                />
            </div>
            <div class="form-group">
                <label class="label-block">Password</label>
                <input
                    type="password"
                    [(ngModel)]="password"
                    name="password"
                    class="form-text"
                    placeholder="Enter a password for this e-mail"
                    min="3"
                    required
                />
            </div>
            <div class="form-group">
                <label class="label-block">Confirm Password</label>
                <input
                    type="password"
                    [(ngModel)]="confirmPassword"
                    name="confirmPassword"
                    class="form-text"
                    placeholder="Retype your password to be sure"
                    required
                />
            </div>
            <div class="form-group">
                <button type="submit" class="btn" [disabled]="isSubmitted && 'disabled'">
                    Submit
                </button>
            </div>
        </form>
    </section>
</div>

// frontend/src/pages/SignUp.tsx
import { useEffect, useState } from "react"
import { FaUser } from "react-icons/fa"

const SignUp = () => {
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    password: "",
    confirmPassword: ""
  })

  const { name, email, password, confirmPassword } = formData

  const onChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData((prevState: any) => ({ ...prevState, [e.target.name]: e.target.value }))
  }

  const onSubmit = (e: React.FormEvent) => {
    e.preventDefault()
  }

  return (
    <div className="container">
      <section className="heading">
        <h1>
          <FaUser /> Sign Up
        </h1>
        <p>Please create an account</p>
      </section>
      <section className="form">
        <form onSubmit={onSubmit}>
          <div className="form-group">
            <label className="form-label" htmlFor="name">
              Name
            </label>
            <input
              type="text"
              className="form-control"
              id="name"
              name="name"
              value={name}
              onChange={onChange}
              placeholder="Enter your full name"
            />
          </div>
          <div className="form-group">
            <label className="form-label" htmlFor="email">
              E-mail
            </label>
            <input
              type="email"
              className="form-control"
              id="email"
              name="email"
              value={email}
              onChange={onChange}
              placeholder="Enter your e-mail address"
            />
          </div>
          <div className="form-group">
            <label className="form-label" htmlFor="password">
              Password
            </label>
            <input
              type="password"
              className="form-control"
              id="password"
              name="password"
              value={password}
              onChange={onChange}
              placeholder="Enter your secret password"
            />
          </div>
          <div className="form-group">
            <label className="form-label" htmlFor="confirmPassword">
              Confirm Password
            </label>
            <input
              type="password"
              className="form-control"
              id="confirmPassword"
              name="confirmPassword"
              value={confirmPassword}
              onChange={onChange}
              placeholder="Reenter your password to confirm"
            />
          </div>
          <div className="form-group">
            <button type="submit" className="btn btn-block">
              Submit
            </button>
          </div>
        </form>
      </section>
    </div>
  )
}

export default SignUp
