// frontend-angular/src/app/pages/signin/signin.component.ts
import { Component, OnInit } from "@angular/core"

@Component({
    selector: "app-signin",
    templateUrl: "./signin.component.html"
})
export class SigninComponent implements OnInit {
    public isLoading = false
    public isSubmitted = false
    public email = ""
    public password = ""

    constructor() {}

    ngOnInit(): void {}

    handleSubmit() {
        this.isSubmitted = true
        this.isLoading = true

        // request sign in

        this.email = ""
        this.password = ""
        setTimeout(() => {
            // router push '/'

            this.isSubmitted = false
            this.isLoading = false
        }, 2000)
    }
}

<app-spinner *ngIf="isLoading"></app-spinner>
<div class="page-container">
    <section class="heading">
        <h1 class="page-title">
            <i class="fa-solid fa-right-to-bracket"></i>
            Sign In
        </h1>
        <p>Inform your credentials to access the dashboard</p>
    </section>
    <section *ngIf="!isLoading" class="form">
        <form (submit)="handleSubmit()">
            <div class="form-group">
                <label class="label-block">E-mail</label>
                <input
                    type="email"
                    [(ngModel)]="email"
                    name="email"
                    class="form-text"
                    placeholder="E-mail address registred"
                    required
                />
            </div>
            <div class="form-group">
                <label class="label-block">Password</label>
                <input
                    type="password"
                    [(ngModel)]="password"
                    name="password"
                    class="form-text"
                    placeholder="user password for this e-mail"
                    min="3"
                    required
                />
            </div>
            <div class="form-group">
                <button type="submit" class="btn" [disabled]="isSubmitted && 'disabled'">
                    Submit
                </button>
            </div>
        </form>
    </section>
</div>

// frontend/src/pages/SignIn.tsx
import { useState } from "react"
import { FaSignInAlt } from "react-icons/fa"

const SignIn = () => {
  const [formData, setFormData] = useState({ email: "", password: "" })

  const { email, password } = formData

  const onChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData((prevState: any) => ({ ...prevState, [e.target.name]: e.target.value }))
  }

  const onSubmit = (e: React.FormEvent) => {
    e.preventDefault()
  }

  return (
    <div className="container">
      <section className="heading">
        <h1>
          <FaSignInAlt /> Sign In
        </h1>
        <p>Inform your credentials to sign in</p>
      </section>
      <section className="form">
        <form onSubmit={onSubmit}>
          <div className="form-group">
            <label className="form-label" htmlFor="email">
              E-mail
            </label>
            <input
              type="email"
              className="form-control"
              id="email"
              name="email"
              value={email}
              onChange={onChange}
              placeholder="Enter your e-mail address"
            />
          </div>
          <div className="form-group">
            <label className="form-label" htmlFor="password">
              Password
            </label>
            <input
              id=""
              className="form-control"
              type="password"
              name="password"
              value={password}
              onChange={onChange}
              placeholder="Enter your secret password"
            />
          </div>
          <div className="form-group">
            <button className="btn btn-block" type="submit">
              Submit
            </button>
          </div>
        </form>
      </section>
    </div>
  )
}

export default SignIn
