// frontend-angular/src/app/app.component.ts
import { Component } from "@angular/core"

@Component({
    selector: "app-root",
    templateUrl: "./app.component.html"
})
export class AppComponent {}

<style>
    .app-container {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        background-color: var(--gray-700);
        color: var(--gray-100);
    }

    main.page-content {
        flex: 1;
    }
</style>

<div class="app-container">
    <app-navbar></app-navbar>
    <main class="page-content">
        <router-outlet class="router-container"></router-outlet>
    </main>
    <app-footer></app-footer>
</div>

// frontend-vuejs-setup/src/App.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue"
import { useStore } from "vuex"

import Navbar from "./components/Navbar.vue"
import Footer from "./components/Footer.vue"
import Spinner from "./components/Spinner.vue"

const store = useStore()

const isLoading = ref(true)

const user = computed(() => store.state.auth.user)

onMounted(() => {
    setTimeout(() => {
        isLoading.value = false
    }, 500)
})
</script>

<template>
    <Navbar class="page-navbar" />
    <div v-if="isLoading">
        <Spinner />
    </div>
    <div v-if="!isLoading" class="app-container">
        <router-view class="router-container"></router-view>
    </div>
    <Footer class="page-footer" />
</template>

<style scoped>
.app-container {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
}

.app-container .router-container {
    flex: 1;
}
</style>
