// frontend-angular/src/app/layout/navbar/navbar.component.ts
import { Component, OnInit } from "@angular/core"

@Component({
  selector: "app-navbar",
  templateUrl: "./navbar.component.html"
})
export class NavbarComponent implements OnInit {
  public user = false

  constructor() {}

  ngOnInit(): void {}

  handleSignOut() {
    console.log("Sign Out")
  }
}

<style>
  header {
    background-color: var(--gray-800);
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 1rem 2rem;
    font-size: 1.2rem;
    margin: 0 0 2rem 0;
  }

  .logo,
  .nav-link {
    color: var(--purple);
    cursor: pointer;
    text-decoration: none;
  }

  .logo {
    font-size: 1.35rem;
  }

  .nav-link {
    margin: 0 17px 0 0;
    color: var(--purple);
  }

  .nav-link:last-child {
    margin: 0;
  }
</style>

<header>
  <a routerLink="/" class="logo">Goals Setter</a>
  <nav *ngIf="!user">
    <a class="nav-link" routerLink="/signin">Sign In</a>
    <a class="nav-link" routerLink="/signup">Sign Up</a>
  </nav>
  <nav *ngIf="user">
    <a class="nav-link" (click)="(handleSignOut)">Sign Out</a>
  </nav>
</header>

// frontend-vuejs/src/components/Navbar.vue
<script lang="ts">
import { defineComponent } from "vue"

export default defineComponent({
  name: "Navbar",
  methods: {
    handleSignOut() {
      console.log("Sign Out")
    }
  }
})
</script>

<template>
  <header>
    <router-link to="/" class="logo">Goals Setter</router-link>
    <nav>
      <router-link class="nav-link" to="/signin">Sign In</router-link>
      <router-link class="nav-link" to="/signup">Sign Up</router-link>
      <a class="nav-link" @click="handleSignOut">Sign Out</a>
    </nav>
  </header>
</template>

<style scoped>
header {
  background-color: var(--gray-800);
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem 2rem;
  font-size: 1.2rem;
  margin: 0 0 2rem 0;
}

.logo,
.nav-link {
  color: var(--purple);
  cursor: pointer;
  text-decoration: none;
}

.logo {
  font-size: 1.35rem;
}

.nav-link {
  margin: 0 17px 0 0;
  color: var(--purple);
}

.nav-link:last-child {
  margin: 0;
}
</style>
