// frontend-vuejs/src/App.vue
<script lang="ts">
import { defineComponent } from "vue"

import Navbar from "./components/Navbar.vue"
import Footer from "./components/Footer.vue"

export default defineComponent({
  name: "App",
  components: { Navbar, Footer }
})
</script>

<template>
  <div class="app-container">
    <Navbar class="page-navbar" />
    <router-view class="router-container"></router-view>
    <Footer class="page-footer" />
  </div>
</template>

<style scoped>
.app-container {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background-color: var(--gray-700);
}

.app-container .router-container {
  flex: 1;
}
</style>

// frontend-angular/src/app/app.component.ts
import { Component } from "@angular/core"

@Component({
    selector: "app-root",
    templateUrl: "./app.component.html"
})
export class AppComponent {}

<style>
    .app-container {
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        background-color: var(--gray-700);
        color: var(--gray-100);
    }

    main.page-content {
        flex: 1;
    }
</style>

<div class="app-container">
    <app-navbar></app-navbar>
    <main class="page-content">
        <router-outlet class="router-container"></router-outlet>
    </main>
    <app-footer></app-footer>
</div>
