// frontend-vuejs-setup/src/components/Spinner.vue
<template>
    <div className="loadingSpinnerContainer">Loading...</div>
</template>

<style scoped>
.loadingSpinnerContainer {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    background-color: rgba(0, 0, 0, 0.5);
    z-index: 5000;
    display: flex;
    justify-content: center;
    align-items: center;

    color: var(--purple);
    font-size: 2.5rem;
}
</style>

// frontend-angular/src/app/components/spinner/spinner.component.ts
import { Component } from "@angular/core"

@Component({
    selector: "app-spinner",
    templateUrl: "./spinner.component.html"
})
export class SpinnerComponent {}

<style>
    .loading-spinner-container {
        position: fixed;
        height: 100vh;
        width: 100vw;
        top: 0;
        left: 0;
        background-color: #000a;
        z-index: 5000;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .loading-spinner {
        width: 200px;
        height: 200px;
        border: 10px solid;
        border-color: var(--purple) transparent var(--lightBlueGreen) transparent;
        border-radius: 50%;
        animation: spin 1.8s linear infinite;
    }

    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }

    .loading-text {
        position: relative;
        top: -0px;
        left: -134px;
    }
</style>

<div class="loading-spinner-container">
    <div class="loading-spinner"></div>
    <div class="loading-text">Loading</div>
</div>
